#include "./xeTai_Chan1/xeTai_Chan1.h"
#include "./xeTai_Chan2/xeTai_Chan2.h"
#include "./xeTai_Cua/xeTai_Cua.h"
#include "./xeTai_Dau/xeTai_Dau.h"
#include "./xeTai_DenSau/xeTai_DenSau.h"
#include "./xeTai_GatNuoc/xeTai_GatNuoc.h"
#include "./xeTai_Guong/xeTai_Guong.h"
#include "./xeTai_Kinh/xeTai_Kinh.h"
#include "./xeTai_NoiThat1/xeTai_NoiThat1.h"
#include "./xeTai_TayNam/xeTai_TayNam.h"
#include "./xeTai_TrucGuong1/xeTai_TrucGuong1.h"
#include "./xeTai_TrucGuong2/xeTai_TrucGuong2.h"

#include "./matTroi/matTroi.h"

#include "./Battery/battery.h"
#include "./Than_Battery/than_battery.h"

#include "./canh1/canh1.h"
#include "./canh2/canh2.h"
#include "./canh3/canh3.h"
#include "./la/la.h"
#include "./than/than.h"

#include "./house/house.h"
#include "./cuachinh/cuachinh.h"
#include "./tayNamCuaChinh/tayNamCuaChinh.h"
#include "./cuaSo1/cuaSo1.h"
#include "./caighe/caighe.h"
#include "./khungfridge/khungfridge.h"
#include "./ngantulanh1/ngantulanh1.h"
#include "./ngantulanh2/ngantulanh2.h"
#include "./canhtulanh1/canhtulanh1.h"
#include "./canhtulanh2/canhtulanh2.h"
#include "./fan/fan.h"
#include "./bed/bed.h"
